data:extend(
{
  {
    type = "int-setting",
    name = "q-tasklist-size",
    setting_type = "startup",
    default_value = 450,
    minimum_value = 10,
    maximum_value = 4000,
    order = "q0",
  },
  {
    type = "bool-setting",
    name = "tas-reach",
    setting_type = "runtime-global",
    default_value = true,
    order = "q1",
  },
  {
    type = "bool-setting",
    name = "tas-reachable",
    setting_type = "runtime-global",
    default_value = true,
    order = "q2",
  },
  {
    type = "bool-setting",
    name = "tas-craft",
    setting_type = "runtime-global",
    default_value = true,
    order = "q3",
  },
  {
    type = "bool-setting",
    name = "tas-burn",
    setting_type = "runtime-global",
    default_value = true,
    order = "q4",
  },
  {
    type = "int-setting",
    name = "tas-reachable-range",
    setting_type = "runtime-global",
    default_value = 15,
    minimum_value = 0,
    maximum_value = 100,
    order = "q5",
  },
  {
    type = "int-setting",
    name = "tas-skip-tick",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 15,
    order = "q6",
  },
  {
    type = "bool-setting",
    name = "tas-craftable",
    setting_type = "runtime-global",
    default_value = true,
    order = "q7",
  },
  {
    type = "bool-setting",
    name = "tas-output",
    setting_type = "runtime-global",
    default_value = true,
    order = "q8",
  },
})